FROM ubuntu:16.04

RUN apt-get update

RUN apt-get install net-tools -y
RUN apt-get install iproute2 -y
RUN apt-get install iputils-ping -y
RUN apt-get install arping -y
RUN apt-get install nano -y
RUN apt-get install build-essential -y
RUN apt-get install libpcap-dev -y
RUN apt-get install tcpdump -y