FROM ubuntu:16.04

RUN apt-get update

RUN apt-get install net-tools -y
RUN apt-get install iproute2 -y
RUN apt-get install nano -y
RUN apt-get install quagga -y
RUN apt-get install telnet -y
RUN apt-get install iptables -y
RUN apt-get install iputils-ping -y
RUN apt-get install tcpdump -y
RUN apt-get install python -y
RUN apt-get install curl -y